/*
** USBAndroidAccessory.h
**
** Copyright © 2009-2011 Future Technology Devices International Limited
**
** THIS SOFTWARE IS PROVIDED BY FUTURE TECHNOLOGY DEVICES INTERNATIONAL LIMITED
** ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
** TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL FUTURE TECHNOLOGY DEVICES
** INTERNATIONAL LIMITED BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
** EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
** OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
** STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
** OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
** DAMAGE.
**
** Header file containing definitions for the USB Android Accessory devices.
**
** Author: FTDI
** Project: Vinculum II Drivers
** Module: Vinculum II USB Slave and USB Host Android Accessory Drivers
** Requires:
** Comments:
**
** History:
**  1 – Initial version
**
*/

#ifndef __USBANDROIDACCESSORY_H__
#define __USBANDROIDACCESSORY_H__

// Definitions obtained from http://developer.android.com/guide/topics/usb/adk.html

// VID and PID definitions for Android Accessories
#define USB_VID_GOOGLE					        		0x18D1
#define USB_PID_ANDROID_ACCESSORY_AVAILABLE        		0x2D00
#define USB_PID_ANDROID_ACCESSORY_ADB_AVAILABLE         0x2D01
#define USB_PID_ANDROID_AUDIO_AVAILABLE                 0x2D02
#define USB_PID_ANDROID_AUDIO_ADB_AVAILABLE             0x2D03
#define USB_PID_ANDROID_ACCESSORY_AUDIO_AVAILABLE       0x2D04
#define USB_PID_ANDROID_ACCESSORY_AUDIO_ADB_AVAILABLE   0x2D05

// Android Accessory interfaces have
//	interface class USB_CLASS_VENDOR (0xff)
//	interface subclass USB_SUBCLASS_VENDOR_VENDOR (0xff)
//	interface protocol USB_PROTOCOL_VENDOR_NONE (0x00)

// Android Accessory Vendor Class-Specific Request Values
//		bRequest										Value
#define USB_ANDROID_ACCESSORY_REQUEST_CODE_GET_PROTOCOL 0x33
#define USB_ANDROID_ACCESSORY_REQUEST_CODE_SEND_STRING	0x34
#define USB_ANDROID_ACCESSORY_REQUEST_CODE_START		0x35
#define USB_ANDROID_ACCESSORY_REQUEST_SET_AUDIO_MODE	0x3A
#define USB_ANDROID_ACCESSORY_REQUEST_REGISTER_HID		0x36
#define USB_ANDROID_ACCESSORY_REQUEST_UNREGISTER_HID	0x37
#define USB_ANDROID_ACCESSORY_REQUEST_SET_HID_REPORT_DESC	0x38
#define USB_ANDROID_ACCESSORY_REQUEST_SEND_HID_EVENT	0x39

// Android Accessory Audio Modes
#define USB_ANDROID_ACCESSORY_SET_AUDIO_MODE_NONE		0
#define USB_ANDROID_ACCESSORY_SET_AUDIO_MODE_16BIT_PCM_2CH_44100KHz	1

// Android Accessory string indices
#define USB_ANDROID_ACCESSORY_STRING_MANUFACTURER		0
#define USB_ANDROID_ACCESSORY_STRING_MODEL				1
#define USB_ANDROID_ACCESSORY_STRING_DESCRIPTION		2
#define USB_ANDROID_ACCESSORY_STRING_VERSION			3
#define USB_ANDROID_ACCESSORY_STRING_URI				4
#define USB_ANDROID_ACCESSORY_STRING_SERIAL_NUMBER		5

#endif                                 /* __USBANDROIDACCESSORY_H__ */
