/*
** USBHostAndroidAccessory.h
**
** Copyright © 2009-2011 Future Technology Devices International Limited
**
** THIS SOFTWARE IS PROVIDED BY FUTURE TECHNOLOGY DEVICES INTERNATIONAL LIMITED
** ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
** TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
** PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL FUTURE TECHNOLOGY DEVICES
** INTERNATIONAL LIMITED BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
** EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
** OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
** INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
** STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
** OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
** DAMAGE.
**
** Header file containing definitions for the USB Host Android Accessory driver.
**
** Author: FTDI
** Project: Vinculum II Drivers
** Module: Vinculum II USB Host Android Accessory Driver
** Requires: vos.h ioctl.h
** Comments:
**
** History:
**  1 – Initial version
**
*/

#ifndef __USBHOSTANDROIDACCESSORY_H__
#define __USBHOSTANDROIDACCESSORY_H__

#include "USB.h"

#define USBHOSTANDROIDACCESSORY_VERSION_STRING "2.0.2"

#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_ATTACH				1
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_DETACH				2
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_GET_PROTOCOL_REVISION 3
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_HAS_ACCESSORY			4
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_HAS_AUDIO				5
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_GET_AUDIO_ENDPOINT	6
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_HAS_ADB				99
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_SEND_HID_DATA				7
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_REGISTER_HID				8
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_UNREGISTER_HID			9
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_SET_HID_REPORT_DESCRIPTOR 10

#define CONTROL_ENDPOINT_MAXIMUM_PACKET_SIZE 8

typedef struct _usbHostAndroidAccessory_ioctl_cb_attach_t
{
    VOS_HANDLE hc_handle;
    char	   *manufacturer;
    char	   *model;
    char	   *description;
    char	   *version;
    char	   *uri;
    char	   *serial;
    /* The following are only required for AOA protocol 2.0 and above. */
    unsigned char mode;     	
} usbHostAndroidAccessory_ioctl_cb_attach_t;

typedef struct _usbHostAndroidAccessory_ioctl_cb_t
{
    unsigned short num_to_write;
    unsigned short *num_written;
	unsigned char deviceID;
    char	   *buffer;	
} usbHostAndroidAccessory_ioctl_cb_t;	

/* Options for attach 'mode' in AOA 2.0 abnd above. */
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_ATTACH_MODE_ACCESSORY 	0
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_ATTACH_MODE_AUDIO		 	0x01
#define VOS_IOCTL_USBHOSTANDROIDACCESSORY_ATTACH_MODE_ADB		 	0x04

/* Return codes. */
enum USBHOSTANDROIDACCESSORY_STATUS {
    USBHOSTANDROIDACCESSORY_OK = 0,
    USBHOSTANDROIDACCESSORY_INVALID_PARAMETER,
    USBHOSTANDROIDACCESSORY_NOT_FOUND,
    USBHOSTANDROIDACCESSORY_NOT_SUPPORTED,
    USBHOSTANDROIDACCESSORY_USBHOST_ERROR = 0x80,
    USBHOSTANDROIDACCESSORY_FATAL_ERROR = 0xFF
};

// USBHOSTANDROIDACCESSORY initialisation function
unsigned char usbHostAndroidAccessory_init(unsigned char vos_dev_num);

#endif                                 /* __USBHOSTANDROIDACCESSORY_H__ */
